# Generated by Django 4.1.7 on 2023-05-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0002_alter_user_requesting_party"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Requesting_party",
            field=models.BooleanField(default=False, verbose_name="Requesting Party"),
        ),
    ]
