# Generated by Django 4.1.7 on 2023-04-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signature", models.CharField(max_length=100)),
                ("receiver", models.CharField(max_length=100)),
                ("token", models.CharField(max_length=100)),
                ("expiry_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
